### ISSUE TITLE
Add their flight plan if they are on frequency.

### ISSUE THREAD

**Issue by cviper13** [Zedruc/ATC24-Suite#36]
**Is your feature request related to a problem? Please describe.**
The problem is when I control people plan their flights by gps direct etc. and when they pass i spend a lot of time finding their flight plan. Also when they divert this happens too.

**Describe the solution you'd like**
maybe add an option that if someone is on my frequency auto import their flight plan if its not has been imported.

**Additional context**
N/A

**Comment by cviper13** [comment]
Another idea: there may be a flight plan list and i can search there easily and fastly import as a strip.

**Comment by cviper13** [comment]
What about https://github.com/Zedruc/ATC24-Suite/issues/36#issuecomment-2111618889 ? @Zedruc

**Comment by Zedruc** [comment]
> What about https://github.com/Zedruc/ATC24-Suite/issues/36#issuecomment-2111618889 ? @Zedruc 

@cviper13 The #flight-plans channel already acts as a list with exactly the same functionality, there's no point in implementing one myself
