### ISSUE TITLE
Radar Rework

### ISSUE THREAD

**Issue by Ycvbii** [Zedruc/ATC24-Suite#37]
yes so idk how to start this yap session but regarding the rework suggestion here is a list ig 

• Import/Add the enroute chart in the radar screen.
By adding or importing i dont mean just put a different photo or wtvr on the top right of the radar screen, add the control zones like the enroute chart toby made, add all the vrps but make them significantly smaller than the other waypoints.

• Change the design of the runway.
By changing the design of the runway i mean remove the old runway design or whatever, and make it only a bold white line (will try to add a picture)

• Change the frequency layout.
Change the frequency layout which is to the right, and put in on the bottom or top in a smaller font

• Add all the SIDS/STARS onto the radar so you could directly pick or search what sids or stars to you want, for example you pick the runway for arrival and departure, you select your active runway(s) so you could choose SID or STAR and it would give you most of the SIDs and STARs regarding your choice. (Yes ik this is a very big suggestion, but atleast add it to the popular airports)

uh done i think

**Comment by Zedruc** [comment]
Just gonna leave this here:
![image](https://github.com/Zedruc/ATC24-Suite/assets/69540929/dcb10dc4-30e2-4d5d-aeec-f96e69b51926)
