### ISSUE TITLE
Make the radar connect with atc24 private server, so it makes controlling easier.

### ISSUE THREAD

**Issue by DragonFishLIVE** [Zedruc/ATC24-Suite#38]
**Describe the solution you'd like**
Is it possible to connect the PTFS ATC 24 roblox server to the radar on ATC 24 Suite? If so, could you please add it? It would make controlling easier.

I hope that is clear enough, if not, please dm me on discord, @DragonFishLIVE

**Comment by axisdadev** [comment]
impossible
thanks for coming to my ted talk

**Comment by Zedruc** [comment]
@axisdadev  perfectly quoted my pinned message.
I'm considering messaging Orange at this point, with little to no hope tho

**Comment by cviper13** [comment]
If Orange doesn't supports this then it is imposable without breaking Roblox ToS.

**Comment by Zedruc** [comment]
> If Orange doesn't supports this then it is impossible without breaking Roblox ToS.

Not impossible since Roblox ToS can't prohibit you from recording your screen, but every solution including this workaround is bound to be very janky

**Comment by cviper13** [comment]
> > If Orange doesn't supports this then it is impossible without breaking Roblox ToS.
> 
> Not impossible since Roblox ToS can't prohibit you from recording your screen, but every solution including this workaround is bound to be very janky

I mean its hard to screen record than parse that screen record opencv etc. Its too complicated. If Orange doesnt allow to have s direct communication between roblox server and atc24suite then no hope.
