### ISSUE TITLE
ATC24 SUITE Bug Report

### ISSUE THREAD

**Issue by UrMemeBoiKevin** [Zedruc/ATC24-Suite#39]
Hello! I'm a controller that often uses ATC24 Suite and I love your website. I just got something happening while controlling. First of all, when I've created a room, the outbound aircraft and VFR aircraft shows up, but not inbounds. Making me having to type in my own inbound strip which is not convenient. And second, this happened a few days ago and is still happening, The three blanks of ATC24 suite strips (Clearance, Ground, Tower) didn't show up making me unable to control. at all. The picture shown below should make you understand more. I hope that you're able to fix it ASAP. Thank you.
![1](https://github.com/Zedruc/ATC24-Suite/assets/170189669/57290e2d-2f38-4162-b0d4-7566f42dfcb8)

**Comment by mseedy** [comment]
Make sure that your 
Hold Arrivals in Arrival List
is not ticked

**Comment by Zedruc** [comment]
* As @mseedy mentioned, make sure you disable "Hold Arrivals in Arrival List"
* If you delete all columns yourself that is saved and next time your configuration loads, well your empty config loads
  * To "resolve" open the settings, all the way at the bottom click the "Reset Lists" button
