### ISSUE TITLE
[BUG]: Rockford Runways Are the Old Ones

### ISSUE THREAD

**Issue by mseedy** [Zedruc/ATC24-Suite#41]
If you go on the ATC24 suite and become CTR at rockford, the runways are still 36L/R and 18L/R not the new ones.
![image](https://github.com/Zedruc/ATC24-Suite/assets/170201137/eca4eaa7-1311-4c66-8b57-9a4f52e16c3f)

**Comment by Zedruc** [comment]
Updated
