### ISSUE TITLE
Touchscreen Compatibility

### ISSUE THREAD

**Issue by GingerHobnob** [Zedruc/ATC24-Suite#43]
Allow the use to select weather they are on pc or on a tablet etc. If they are on a tablet, increase the strip size & allow the user to write data instead of typing.

**Comment by AviatorMax2020** [comment]
Would definitely be a good thing to have for tablets, and would make using strips in events so much easier for some *cough cough*

**Comment by Zedruc** [comment]
1. Touch screen compatibility would certainly mean I'd need to redo the whole thing, which I'm not doing
2. I'm convinced that most ATC who take the realism seriously do posess a computer with at least one monitor, therfore also a keyboard to use
