### ISSUE TITLE
Different Separation System

### ISSUE THREAD

**Issue by GingerHobnob** [Zedruc/ATC24-Suite#44]
Instead of a 'Tick Box' system, have FS separators with custom names (e.g. Cleared, Push, Taxi, etc) and allow users to click and drag the FS below these separators. I think it would make the whole system easier to see and undsertand (instead of having to search for one specific a/c to update the staus).

**Comment by Zedruc** [comment]
I'm not quite sure what you mean by "Tick Box" System, there's not a single box to tick regarding strips or their lists.
Drag and Drop has been answered before, just too complicated to implement in hindsight as to how simple this application is.
