### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by vtolvr** [Zedruc/ATC24-Suite#45]
**Describe the bug**
The ground chart image does not show on any airport.

**To Reproduce**
1. Select any airport

**Expected behavior**
To select an airport and see the ground chart.

**Screenshots**
![Screenshot 2024-05-25 141651](https://github.com/Zedruc/ATC24-Suite/assets/113134107/c42c428d-f124-47db-925e-5ff03e7f0e0e)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Google Chrome v125.0.6422.78

**Additional context**

**Comment by Zedruc** [comment]
ptfs.xyz was down, that's the chart provider
