### ISSUE TITLE
[BUG]: Creating a room and connecting to discord won't work.

### ISSUE THREAD

**Issue by OPrice16** [Zedruc/ATC24-Suite#48]
**Describe the bug**
Clicking create room button doesn't work and brings up an error message (self explanatory in the first screenshot). I pressed OK and brings me to the page of the second screenshot which I press AUTHORISE and is stuck there with the elipses for an endless amount of time. I even try reloading the page but it's the same outcome.

**To Reproduce**
1. Go to 'ATC24 suite'.
2. Click on 'create room'.
3. Scroll down to 'N/A'.
4. See error.
5. Press 'OK'.
6. Press 'Authorise'.
7. issue is that.

**Expected behavior**
Expect to be waiting, looking at the elipses after you press authorise for a longggggggggg time.

**Screenshots**
![image](https://github.com/Zedruc/ATC24-Suite/assets/173058308/360471e9-dc29-47ef-8e25-dd06b40dbbce)
![image](https://github.com/Zedruc/ATC24-Suite/assets/173058308/86de78ae-6bff-42c6-a7ca-599756d7c374)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser bing

**Additional context**
N/A

**Comment by graxe20** [comment]
This was resolved, it was just an internet issue.

**Comment by Zedruc** [comment]
Internet issues and the Database not liking it, was resolved on the same day
