### ISSUE TITLE
[BUG]: I keep getting the error: Error! Your client has made an unauthorized request to the ATC24-Suite.  Please make sure you've connected your Discord account and reload the page. I dit everything and it still doesn't work

### ISSUE THREAD

**Issue by ijnstijn** [Zedruc/ATC24-Suite#49]
I keep getting the error: Error! Your client has made an unauthorized request to the ATC24-Suite. Please make sure you've connected your Discord account and reload the page. I dit everything and it still doesn't work

**Comment by graxe20** [comment]
This was resolved, it was just Zedruc's ISP deciding to die.

**Comment by Zedruc** [comment]
Internet issues and the Database not liking it, was resolved on the same day
