### ISSUE TITLE
[BUG]: Mu account and discord

### ISSUE THREAD

**Issue by Kazu1503Juju** [Zedruc/ATC24-Suite#51]
**infinity loading disorde**

**To Reproduce**
1. Go to 'the site'
2. Click on just wait'
3 github says that I asked for something bad
4 And it says to verify my disorde acount
5 And when i click allowed that go to infinity loading

What the problem pls ?

**Comment by graxe20** [comment]
This was resolved, it was a network issue on Zedruc's side :)

**Comment by Zedruc** [comment]
Internet issues and the Database not liking it, was resolved on the same day
