### ISSUE TITLE
[BUG]: Larnaca not filing flight plans from the channel automatically

### ISSUE THREAD

**Issue by DanilTheBestPilot** [Zedruc/ATC24-Suite#53]
**Describe the bug**
simple
**To Reproduce**

**Expected behavior**
that automatically filing flight plans from the channel
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
browser opera gx
**Additional context**

**Comment by cviper13** [comment]
Create room, enable import setting, disable "hold in  arrival list", disable "Only event flightplans"  If all fails reset website data and log in again, that fixed  it for everyone so far

By @Zedruc from atc24 faq
