### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Sheepdude289** [Zedruc/ATC24-Suite#55]
**Describe the bug**
autoloading flight plans

**To Reproduce**
1. Go to settings
2. Click on "Automatically import flightplans from ATC24 (Requires user to be in a room)"
3. Create a room
4. File a flight plan, then it fails to load.

**Expected behavior**
I expect any future flightplans to be automatically filed in strips after that setting is enabled.

**Screenshots**
![image](https://github.com/user-attachments/assets/fe357a6f-9fda-46b7-a6b8-c1c79d087471)

**Desktop (please complete the following information):**
 - OS: windows 11
 - browser: Brave (it has been a problem on google chrome as well)

**Additional context**
it has happened to me as well as my friend.

**Comment by Zedruc** [comment]
Check the FAQ in the Discord and make sure the flight strip isn't imported in an off-screen list. In case of doubt delete website data and reload
