### ISSUE TITLE
BUG: Alaska Callsign

### ISSUE THREAD

**Issue by Coolman6598** [Zedruc/ATC24-Suite#61]
**Describe the bug**
When you include an ICAO Airline Code (or when the full airline is listed out), the callsign appears under it. However, for what I believe to be Alaska Airlines - ASA - The callsign appears as "Inc." I checked [The Airline Callsign List](https://en.wikipedia.org/wiki/List_of_airline_codes) and the official callsign is "Alaska".

**To Reproduce**
1. Add a flight plan into the suite
2. Include "ASA" as the filed callsign

**Expected behavior**
Expected "Alaska" to appear under the callsign.

**Screenshots**
![Alaska Bug](https://github.com/user-attachments/assets/3c898af7-3453-4519-b0bd-e2e9462902f8)

**Yes, Pointless**
the shi aint even in ptfs sorry😭

**Comment by Zedruc** [comment]
Yeah, pointless
