### ISSUE TITLE
[BUG]: Flight plan not going to ATC24 Suite

### ISSUE THREAD

**Issue by ChessMasterAF** [Zedruc/ATC24-Suite#65]
IT says if you enable one of the settings, the flights from flight plan, both arrivals and departures will be posted in flight-plan. but it doesn't work. I went to the voice channel and it didn't work.

**Comment by Zedruc** [comment]
1. No need to be in voice chat for the suite to work
2. Disable "Hold Arrivals in Arrival List"
3. Make sure you are in a room, otherwise it doesn't work

Read the help page.

**Comment by ChessMasterAF** [comment]
It would be nice as I usually don't know where the plane is coming from and who is it especially as I don't have the ATC gamess so I mainly use the map and knowing which aircraft is coming here in which direction and what callsign it has greatly helps
