### ISSUE TITLE
Add RAF Scampton to the suite

### ISSUE THREAD

**Issue by tablewizzy** [Zedruc/ATC24-Suite#66]
**Is your feature request related to a problem? Please describe.**
Self explanatory

**Describe the solution you'd like**
Addition of RAF Scampton to the suite 

**Additional context**
N/A

**Comment by CrossTR15YT** [comment]
No.

Thanks for listening to my TED talk.

_I informally represent Zedruc_

**Comment by awdev1** [comment]
Crazy

**Comment by Zedruc** [comment]
No

**Comment by CrossTR15YT** [comment]
Told ya
