### ISSUE TITLE
[BUG]: logging on issue

### ISSUE THREAD

**Issue by kaarkuzo** [Zedruc/ATC24-Suite#68]
**Describe the bug**
alwyas says i have another account/device logged onto discord making me unable to use atc24 suite

**To Reproduce**
1. Go to atc24 suite
2. Click on -
3. Scroll down to -

**Expected behavior**
no error should pop up when im using the atc24 suite

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: [ipad gen 9]
 - Browser [discord]

**Additional context**
-

**Comment by Zedruc** [comment]
All iOs devices seem to share this issue;
And Discord is not a bowser
