### ISSUE TITLE
Add a CLR status (clearance given) to the list of cyclable strip statuses

### ISSUE THREAD

**Issue by ONDER1E** [Zedruc/ATC24-Suite#69]
Very painful to swap controllers and the new controller has no idea if any of the stations have been cleared their IFR/VFR clearance. Also helpful in general to ensure you dont clear someone twice.

Solution: Add CLR before SUG

**Comment by Zedruc** [comment]
SUG = Clearance Received for simplicity, based on the german phraseology I'm used to since I'm the developer

`DLH 160, Information Golf correct, *Startup Approved, cleared ...`
