### ISSUE TITLE
[BUG]: countinued saying logged into motible ACCTS

### ISSUE THREAD

**Issue by BROSKIELIKEWHAT** [Zedruc/ATC24-Suite#71]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]

**Additional context**

**Comment by Zedruc** [comment]
Make sure you *do not*
* Forcibly close the browser while the suite is open (e.g. Alt+F4, Kill it with Taskmanager)
* Shut down your PC with the browser and suite open

All these things keep the suite from logging you out
