### ISSUE TITLE
[BUG]: error on login 

### ISSUE THREAD

**Issue by Yongkhing1234** [Zedruc/ATC24-Suite#72]
**Describe the bug**
When i log in it says error 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [IOS IPHONE 14]

**Additional context**

**Comment by Zedruc** [comment]
Make sure you *do not*
* Forcibly close the browser while the suite is open (e.g. Alt+F4, Kill it with Taskmanager)
* Shut down your PC with the browser and suite open

All these things keep the suite from logging you out
