### ISSUE TITLE
mellor callsigns

### ISSUE THREAD

**Issue by AirbusA380AX** [Zedruc/ATC24-Suite#73]
**Is your feature request related to a problem? Please describe.**
There is no option to select "APP/RADAR" for Mellor when selecting your atc station
**Describe the solution you'd like**
Add "radar" to the station selection for Mellor

**Additional context**
N/A

**Comment by Zedruc** [comment]
Very good call, also useful for the event this evening. Fixed with version `b-3.6.20`
